### ISSUE TITLE
Some events wouldn't fire

### ISSUE THREAD

**Issue by coolacid** [nodecg/nodecg#152]
Was testing the new version tonight just before stream and sometimes events wouldn't fire. I don't know if this is related to THIS issue, but it is an error fired during the test. Streamer was just about to go live so didn't have time to fully dig. 

```
Missing error handler on `socket`.
TypeError: handler.func is not a function
    at /home/node/nodecg/lib/api.js:93:15
    at Array.forEach (native)
    at Socket.<anonymous> (/home/node/nodecg/lib/api.js:90:27)
    at emitTwo (events.js:105:20)
    at Socket.emit (events.js:185:7)
    at Socket.onevent (/home/node/nodecg/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/node/nodecg/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/node/nodecg/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/node/nodecg/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/node/nodecg/node_modules/socket.io-parser/index.js:247:12)
```

**Comment by Lange** [comment]
I believe this error is happening because something that you've passed to `nodecg.listenFor` is not a function. I have pushed up a commit that should throw a more informative error when this erroneous assignment happens. Pull down that commit and you should see an error on page load that sheds more light on the source of the problem.

**Comment by coolacid** [comment]
We couldn't get lfg-streamtip to reset daily, and just prior to ^ was the resetPeriod - daily message. Post stream I'll look into it more.

**Comment by coolacid** [comment]
Closing in favor of https://github.com/SupportClass/lfg-streamtip/issues/2
