### ISSUE TITLE
Dashboard sometimes will not load after restarting NodeCG

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#275]
This doesn't seem to be 100% consistent but here's what I think are the repro steps:

1. Start NodeCG v0.9.x
2. Open the dashboard
3. Restart NodeCG
4. Try refreshing the dashboard -- sometimes it will never load

**Comment by Lange** [comment]
I actually haven't been able to repro this with the most recent changes, so I might have accidentally fixed it?

**Comment by Lange** [comment]
I haven't been able to repro this after lots of attempts. The bug seems to have changed to this: https://github.com/nodecg/nodecg/issues/289

**Comment by Lange** [comment]
I'm getting hit with this bug hard now, I have no idea what is causing it. Any investigative help from people would be very, very appreciated.

**Comment by Lange** [comment]
Okay, this, #289, and #303 are absolutely related. I updated the version of `deasync` being used and it seemed to make the problem _better_, but it did not completely go away. After that, completely removed all use of `deasync` (which means breaking schemas with external `$ref`s in them) and I haven't had this issue pop up once. 

Something about the use of `deasync` here is completely breaking NodeCG's ability to send or receive any external connections. HTTP and WebSockets will both fail when this issue comes up. I have no idea why this sometimes happens or what the underlying cause is. And, again, this does not happen all the time. If I restart NodeCG enough it will eventually not happen. I leave for SGDQ in 2 days and I don't know that I'm going to have time to debug this on my own. I need help.

The most direct solution would be to refactor the relevant code such that we can remove the `deasync` dependency. Failing that, someone might be able to figure out what exactly is breaking by having a test bundle that uses external `$ref`s in its replicant schemas. I think that this issue only comes up when using those? Not 100% sure.

**Comment by Lange** [comment]
The relevant code is [lib/replicant/replicant.js#L89-L93](https://github.com/nodecg/nodecg/blob/0.9-dev/lib/replicant/replicant.js#L89-L93) on the 0.9-dev branch. `dereferenceSchema` is a `deasync`-wrapped version of `json-schema-ref-parser`'s `dereference` method. The wrap happens on [line 14](https://github.com/nodecg/nodecg/blob/0.9-dev/lib/replicant/replicant.js#L14).

**Comment by Lange** [comment]
Another clue: sometimes when this bug happens, I see the `Schema could not be loaded, are you sure that it is valid JSON?` error message from [lib/replicant/replicant.js#L97](https://github.com/nodecg/nodecg/blob/0.9-dev/lib/replicant/replicant.js#L97). This is further evidence that the issue is something going wrong with our usage of `deasync`.

**Comment by Lange** [comment]
Strictly speaking, for my own use case it would be okay if we only supported `$ref` to files on the local disk. We don't need support for fetching schemas from the web. This means that we could just use `fs.readFileSync`, which would let us not have to use `deasync` at all.

**Comment by farfabet** [comment]
deasync is bragging to avoid devs having to use a while(!done) loop. would use such a loop solve the issue ?

**Comment by farfabet** [comment]
```js
try {
	var done = false;
	var mySchema = null;
	var myErr = null;
	$RefParser.dereference(absoluteSchemaPath, function(err, schema) {
		myErr = err;
		mySchema = schema;
		done = true;
	});
	while (!done) 
		sleep(10);
	/*this.schema = dereferenceSchema(absoluteSchemaPath, {
		dereference: {
			circular: false
		}
	});*/
	// TODO handle err
	this.schema = mySchema;
	this.schemaSum = sha1(this.schema);
	this.validate = shared.generateValidator(this);
} catch (e) {
	this.log.error('Schema could not be loaded, are you sure that it is valid JSON?');
	this.log.error(e.stack);
}

```

**Comment by Lange** [comment]
@farfabet what is the `sleep` function in that example? `sleep` is not a function in JavaScript/Node.js.

**Comment by farfabet** [comment]
Oh... Sorry not used to node yet :)
May be you could just use the sleep wrapper from deasync. you'd keep the dependency but as a simpler level, it might not mess things up.
```
require('deasync').sleep(100);
```

**Comment by farfabet** [comment]
Or may be use this stackoverflow tips without deasync : https://stackoverflow.com/posts/39914235/revisions

```
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function demo() {
  console.log('Taking a break...');
  await sleep(2000);
  console.log('Two second later');
}

demo();
```

**Comment by Lange** [comment]
Class constructors cannot be asynchronous. Even if they could, making the Replicant constructor asynchronous would be a _major_ breaking change, and would require that large portions of NodeCG be rewritten. I use `deasync` here because the code in this constructor _must_ remain synchronous.

**Comment by farfabet** [comment]
I might be missing something, how is this snippet asynchronous ? it does call an async function but keep looping in its scope until the async task is done. Therefor the constructor seems sync to me, isn't it ?

```
console.log("before async task");
$RefParser.dereference(absoluteSchemaPath, function(err, schema) {
	myErr = err;
	mySchema = schema;
	done = true;
});
while (!done)  {
	console.log("wait until it's done");
	require("deasync").sleep(10);
}
console.log("done");
```
produces
```
info: [nodecg/lib/server] Starting NodeCG 0.9.0-beta (Running on Node.js v6.11.0)
Verifying/installing npm deps for bundle lange-notify... done!
Verifying/installing npm deps for bundle lfg-filter... done!
Verifying/installing npm deps for bundle lfg-nucleus... done!
before async task
wait until it's done
wait until it's done
done
info: [nodecg/lib/server/extensions] Mounted lfg-filter extension
info: [nodecg/lib/server/extensions] Mounted lfg-nucleus extension
info: [nodecg/lib/server] NodeCG running on http://localhost:9090
```

Seems legit to me.

**Comment by Lange** [comment]
I was referring to your StackOverflow link. `async function demo` is an async function.

**Comment by Lange** [comment]
I did some experimenting with using `deasync`'s `sleep` method instead of wrapping `json-schema-ref-parser`'s `dereference` method. This let me add more logging and gain more insight into the issue, but my data is still inconclusive:

It seems that there may be several issues at play. One issue is that somehow, `deasync` was defeating the memoization strategy of the server-side Replicant library (`lib/replicant.js`). I don't yet understand how it was doing this, but I was definitely seeing Replicants attempt to be declared multiple times simultaneously, instead of returning the cached result. I modified the memoization to work around this problem, and the core issue became less common, but did not go away completely.

I also added much more logging, and it seems that sometimes `deasync` itself is preventing `$RefParser.dereference` from completing. There are rare occasions where `dereference` simply will not complete until `deasync` stops. I am unsure why this is, or why it would only happen some of the time.

**Comment by Lange** [comment]
I commented on https://github.com/abbr/deasync/issues/40, which _might_ be the same issue as what I'm having? I don't know enough about Node.js' internals and libUV to say for sure.

**Comment by Lange** [comment]
The fastest solution here might be to fork `json-schema-ref-parser` to use `fs.readFileSync` instead of `fs.readFile` (see [json-schema-ref-parser/lib/resolvers/file.js#L38-L65](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/8154cf149ac8d5297e8336c1e724f00046b0711d/lib/resolvers/file.js#L38-L65))

**Comment by Lange** [comment]
There is an issue open on `json-schema-ref-parser` requesting a synchronous API, but chances are that I can't wait for that to happen and I'll need to implement something myself before I leave for SGDQ. https://github.com/BigstickCarpet/json-schema-ref-parser/issues/14

**Comment by Lange** [comment]
Got a really wild error just now that I've never seen before. It's presumably related but I can't be 100% certain:

```
"C:\Program Files (x86)\JetBrains\WebStorm 2016.2.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\index.js
[nodecg] Developer mode is active! Be sure to disable this in production.
info: [nodecg/lib/server] Starting NodeCG 0.9.0-beta (Running on Node.js v8.1.2)
Verifying/installing npm deps for bundle sgdq17-layouts... done!
warn: [nodecg/lib/dashboard] Serving unbundled files for development
DECLARING: _singleInstance liveSocketIds
DECLARING: _sounds volume:master
DECLARING: sgdq17-layouts assets:sponsors-3ds
DECLARING: sgdq17-layouts assets:sponsors-gameboy_1
DECLARING: sgdq17-layouts assets:sponsors-gba_1
DECLARING: sgdq17-layouts assets:sponsors-gba_2
DECLARING: sgdq17-layouts assets:sponsors-standard_1
DECLARING: sgdq17-layouts assets:sponsors-standard_2
DECLARING: sgdq17-layouts assets:sponsors-standard_3
DECLARING: sgdq17-layouts assets:sponsors-widescreen_1
DECLARING: sgdq17-layouts assets:sponsors-widescreen_2
warn: [sgdq17-layouts] WARNING! useMockData is true, you will not receive real data from the tracker!
DECLARING: sgdq17-layouts gdq:currentLayout
DONE! gdq:currentLayout
DECLARING: sgdq17-layouts _obs:namespaces
DONE! _obs:namespaces
DECLARING: sgdq17-layouts streamingOBS:websocket
DONE! streamingOBS:websocket
DECLARING: sgdq17-layouts streamingOBS:programScene
DONE! streamingOBS:programScene
DECLARING: sgdq17-layouts streamingOBS:previewScene
DONE! streamingOBS:previewScene
DECLARING: sgdq17-layouts streamingOBS:sceneList
DONE! streamingOBS:sceneList
DECLARING: sgdq17-layouts streamingOBS:transitioning
DONE! streamingOBS:transitioning
DECLARING: sgdq17-layouts recordingOBS:websocket
DONE! recordingOBS:websocket
DECLARING: sgdq17-layouts recordingOBS:programScene
DONE! recordingOBS:programScene
DECLARING: sgdq17-layouts recordingOBS:previewScene
DONE! recordingOBS:previewScene
DECLARING: sgdq17-layouts recordingOBS:sceneList
DONE! recordingOBS:sceneList
DECLARING: sgdq17-layouts recordingOBS:transitioning
DONE! recordingOBS:transitioning
DECLARING: sgdq17-layouts currentPrizes
DECLARING: sgdq17-layouts allPrizes
info: [sgdq17-layouts] Polling prizes every 60 seconds...
DECLARING: sgdq17-layouts currentBids
DECLARING: sgdq17-layouts allBids
info: [sgdq17-layouts] Polling bids every 60 seconds...
DECLARING: sgdq17-layouts total
DECLARING: sgdq17-layouts autoUpdateTotal
info: [sgdq17-layouts] Automatic updating of donation total enabled
DECLARING: sgdq17-layouts checklistComplete
DONE! checklistComplete
DECLARING: sgdq17-layouts currentRun
DONE! currentRun
DECLARING: sgdq17-layouts stopwatch
DECLARING: sgdq17-layouts nowPlayingPulsing
DECLARING: sgdq17-layouts nowPlaying
DECLARING: sgdq17-layouts countdown
DECLARING: sgdq17-layouts countdownRunning
DECLARING: sgdq17-layouts caspar:files
DONE! caspar:files
warn: [sgdq17-layouts:caspar] Disconnected.
DECLARING: sgdq17-layouts currentIntermission
info: [sgdq17-layouts:caspar] [osc] Port open, can now receive events from CasparCG.
DONE! currentIntermission
DECLARING: sgdq17-layouts schedule
info: [sgdq17-layouts:tracker] Logging in as lange...
DECLARING: sgdq17-layouts twitch:timeSinceLastAd
DECLARING: sgdq17-layouts twitch:timeLeftInAd
warn: [sgdq17-layouts] "twitter" is not defined in cfg/sgdq17-layouts.json! Twitter integration will be disabled.
warn: [sgdq17-layouts] "osc" is not defined in cfg/sgdq17-layouts.json! Behringer X32 OSC integration will be disabled.
DECLARING: sgdq17-layouts interview:lowerthirdTimeRemaining
DECLARING: sgdq17-layouts interview:lowerthirdShowing
DECLARING: sgdq17-layouts interview:questionTimeRemaining
DECLARING: sgdq17-layouts interview:questionShowing
error: [Replicant/sgdq17-layouts.interview:questionShowing] Schema could not be loaded, are you sure that it is valid JSON?
 TypeError: Cannot read property 'aborted' of null
    at ClientRequest._req.on (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\bundles\sgdq17-layouts\node_modules\ws\lib\WebSocket.js:640:18)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
    at Function.module.exports.loopWhile (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\deasync\index.js:71:11)
    at C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\deasync\index.js:44:19
    at Replicant (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\replicant\replicant.js:116:7)
    at new NodeCG.Replicant (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\api.js:375:9)
    at NodeCG.Replicant (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\api.js:435:9)
    at Object.<anonymous> (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\bundles\sgdq17-layouts\extension\interview.js:18:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\bundles\sgdq17-layouts\extension\index.js:69:3)
    at _loadExtension (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\server\extensions.js:99:37)
    at EventEmitter.module.exports.init (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\server\extensions.js:32:6)
    at bundleManager.init.then (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\lib\server\index.js:127:20)
    at tryCatcher (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._settlePromise (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:582:21)
    at Promise._settlePromise0 (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\vanca\Documents\Programming\nodecg\nodecg-v0.9\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
DECLARING: sgdq17-layouts interview:questionSortMap
info: [sgdq17-layouts] Donation total unchanged, not updated
DONE! interview:questionShowing
DONE! interview:questionSortMap
DECLARING: sgdq17-layouts interview:questionTweets
DONE! interview:questionTweets
DECLARING: sgdq17-layouts interview:names
Error: async hook stack has become corrupted (actual: 27564, expected: 900)
info: [nodecg/lib/server/extensions] Mounted sgdq17-layouts extension
info: [nodecg/lib/server] NodeCG running on http://localhost:9090
```

**Comment by Lange** [comment]
Closing in favor of #303.
