### ISSUE TITLE
Rare issue caused by deasync when loading schemas

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#289]
If you load the dashboard and restart NodeCG at just the right time, you'll get an error like this:
```
Error: Request aborted
    at onaborted (C:\Users\vanca\Documents\Programming\nodecg\0.8\node_modules\express\lib\response.js:984:15)
    at Immediate.<anonymous> (C:\Users\vanca\Documents\Programming\nodecg\0.8\node_modules\express\lib\response.js:1026:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at Function.module.exports.loopWhile (C:\Users\vanca\Documents\Programming\nodecg\0.8\node_modules\deasync\index.js:72:22)
    at C:\Users\vanca\Documents\Programming\nodecg\0.8\node_modules\deasync\index.js:44:19
    at Replicant (C:\Users\vanca\Documents\Programming\nodecg\0.8\lib\replicant\replicant.js:87:20)
    at new NodeCG.Replicant (C:\Users\vanca\Documents\Programming\nodecg\0.8\lib\api.js:298:9)
    at NodeCG.Replicant (C:\Users\vanca\Documents\Programming\nodecg\0.8\lib\api.js:358:9)
    at Object.<anonymous> (C:\Users\vanca\Documents\Programming\nodecg\0.8\bundles\REDACTED\extension\importer\project-import.js:39:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at asyncInitTasks (C:\Users\vanca\Documents\Programming\nodecg\0.8\bundles\REDACTED\extension\index.js:43:4)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Lange** [comment]
Closing as a duplicate of #275.
