### ISSUE TITLE
Uploading or modifying assets crashes NodeCG server

### ISSUE THREAD

**Issue by hedgehog1029** [nodecg/nodecg#455]
When trying to upload or modify assets (either via the web panel or live-renaming the local file), the NodeCG server crashes due to an unhandled exception:

```js
UNCAUGHT EXCEPTION! NodeCG will now exit.
TypeError: replicantsByNamespace[uploadedFile.namespace][uploadedFile.category].value.push is not a function
    at sha1File ([nodecg-root]/lib/assets/index.js:118:79)
    at ReadStream.<anonymous> ([nodecg-root]/node_modules/sha1-file/index.js:21:14)
    at ReadStream.emit (events.js:187:15)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by Lange** [comment]
Possibly related to https://github.com/nodecg/nodecg/issues/426

**Comment by hedgehog1029** [comment]
just for the record: no components of the filepath contain any special characters, it's all just lowercase ascii

**Comment by Lange** [comment]
Got it. I'm not immediately sure what the issue as, as I seem to be unable to repro it. Is anyone else able to repro?

@hedgehog1029 does this issue only happen with a certain bundle, or only with certain files?

**Comment by hedgehog1029** [comment]
I only have one bundle installed right now - it's based off the yeoman generator so I don't think I've done anything too weird?

Error occurs [here](https://github.com/nodecg/nodecg/blob/518cf2124333ae54c2eab9da02b914146971ccb1/lib/assets/index.js#L118) in nodecg - seems like maybe bundles initializing replicants badly can cause full crashes?

**Comment by Hoishin** [comment]
Would it be possible to provide a bundle repo that can reproduce this issue? Cannot be sure if it's bundle related or core's problem.

**Comment by hedgehog1029** [comment]
apologies for going dark on this - got pushed to the back of my mind while working on other things! I have a [Sentry error report](https://sentry.io/share/issue/6eb8280bc0364afeb717894920094be4/) from this error.

The only place where I access the replicant is in a dashboard:
```js
var jingles = nodecg.Replicant("assets:jingles", { defaultValue: [] });

jingles.on("change", (val) => app.jingles = val);
```

**Comment by Kipples** [comment]
I ran into this issue myself, I worked around it by deep cloning the replicant value.
