### ISSUE TITLE
When we send a malformed json, nodecg reply by display **stacktrace** in html page.

### ISSUE THREAD

**Issue by benoitDD** [nodecg/nodecg#511]
Hello,

When we send a request HTTP malformed json, nodecg reply by display **stacktrace** in html page.

example: we send to nodecg:
```
{
	"malformed-json": "forget a double quote!
}
```

Nodecg reply in html page by display the **stacktrace**:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>SyntaxError: Unexpected token <br> in JSON at position 44<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (C:\Users\toto\Documents\tools\nodecg\v0.2\node_modules\body-parser\lib\types\json.js:89:19)<br> &nbsp; &nbsp;at C:\Users\toto\Documents\tools\nodecg\v0.2\node_modules\body-parser\lib\read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (C:\Users\toto\Documents\tools\nodecg\v0.2\node_modules\raw-body\index.js:224:16)<br> &nbsp; &nbsp;at done (C:\Users\toto\Documents\tools\nodecg\v0.2\node_modules\raw-body\index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\toto\Documents\tools\nodecg\v0.2\node_modules\raw-body\index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:203:15)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (domain.js:448:20)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1129:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
</body>

</html>
```

How hide this behavior ? (hide the stacktrace in html page)

**Comment by Lange** [comment]
I agree that NodeCG should not return stacktraces. Let's fix this for v2.0
