### ISSUE TITLE
`nodecg install` git repository fails due to new git protocol changes

### ISSUE THREAD

**Issue by Tempystral** [nodecg/nodecg#595]
## Issue
Github recently sunset its unofficial `git://` protocol, and as a result any application trying to use it will face issues. This is the case for ``nodecg install``, which currently fails with the following error:

```
Fetching obs-control release list... fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
failed!
Error: Command failed: git ls-remote --refs --tags git://github.com/nicnacnic/obs-control.git
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.default_1 [as default] (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/dist/lib/fetch-tags.js:5:37)
    at Command.action (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/dist/commands/install.js:53:36)
    at Command.listener [as _actionHandler] (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/node_modules/commander/index.js:970:12)
    at Command.parse (/home/tempystral/.nvm/versions/node/v17.7.2/lib/node_modules/nodecg-cli/node_modules/commander/index.js:801:10)
```

## Workround
I don't actually know how to solve this issue, but at least for now we can install packages by cloning them directly into `bundles/`.

**Comment by hlxid** [comment]
This was already reported in the cli repository and already has a PR fixing it: https://github.com/nodecg/nodecg-cli/issues/89

**Comment by Tempystral** [comment]
Oh, of course. It somehow passed me by that there was another project for the cli, no wonder I didn't find any reports about that here.

Thanks, I'll close this issue.
