### ISSUE TITLE
Cheerio breaking change causes any bundles with panels to crash nodecg on a fresh install

### ISSUE THREAD

**Issue by Corvimae** [nodecg/nodecg#752]
Installing nodecg via `nodecg setup` and starting it up with any bundles that define dashboard panels causes this error:

```
TypeError: Cannot read properties of undefined (reading 'load')
    at <anonymous> (/home/archen/nodecg-nsg/src/server/bundle-parser/panels.ts:54:21)
    at Array.forEach (<anonymous>)
    at default_1 (/home/archen/nodecg-nsg/src/server/bundle-parser/panels.ts:36:18)
    at default_1 (/home/archen/nodecg-nsg/src/server/bundle-parser/index.ts:48:23)
    at <anonymous> (/home/archen/nodecg-nsg/src/server/bundle-manager.ts:185:31)
    at Array.forEach (<anonymous>)
    at <anonymous> (/home/archen/nodecg-nsg/src/server/bundle-manager.ts:161:18)
    at Array.forEach (<anonymous>)
    at BundleManager (/home/archen/nodecg-nsg/src/server/bundle-manager.ts:100:16)
    at NodeCGServer.<anonymous> (/home/archen/nodecg-nsg/src/server/server/index.ts:205:25)
```

This line is `cheerio.load`; the cheerio issues page has a lot of issues involving them going from 1.0.0-rc12 to 1.0.0 with a bunch of breaking changes. (https://github.com/cheeriojs/cheerio/issues/4044, https://github.com/cheeriojs/cheerio/issues/4103)

Installing via `nodecg setup` installed 1.0.0, which does not work properly; cloning from git directly and building works as expected, as 1.0.0-rc12 is installed. I'm not sure the mechanisms behind `nodecg setup`, it might not be respecting the package lock properly.

**Comment by noahm** [comment]
This is was fixed in #748 and is just waiting on a release to go out.

**Comment by Corvimae** [comment]
oh cool! Is there any ETA on that release? obviously there's a workaround w/ just doing a git clone but it pretty much means the CLI is busted for new installs in the interim

**Comment by noahm** [comment]
this just got a release in #754

**Comment by noahm** [comment]
@Hoishin now that the release is published, can you close this too?

**Comment by Hoishin** [comment]
> @Hoishin now that the release is published, can you close this too?

Would you be able to test and confirm the issue not happening with the latest version?

**Comment by noahm** [comment]
Can confirm everything is working as expected with the CLI and the latest version!

**Comment by Hoishin** [comment]
@noahm Thank you so much!
