### ISSUE TITLE
app.use() required middleware functions

### ISSUE THREAD

**Issue by Tamfoolery** [nodecg/nodecg#92]
I'm getting error below whenever my bundle is loaded in, which then breaks the admin panel and I assume everything else!

The issue doesn't appear to be in my code, as I've tried running with the full code, just the basic initialization of the express app, and no initialization what so ever and they all return the same error.

```
error: [nodecg/lib/bundles]  TypeError: app.use() requires middleware functions
    at EventEmitter.use (E:\NodeCG\nodecg\node_modules\express\lib\application.js:177:11)
    at E:\NodeCG\nodecg\lib\server\index.js:58:17
    at Array.forEach (native)
    at EventEmitter.<anonymous> (E:\NodeCG\nodecg\lib\server\index.js:57:49)
    at EventEmitter.emit (events.js:92:17)
    at EventEmitter.exports.getExtensions (E:\NodeCG\nodecg\lib\server\extensions.js:61:13)
    at EventEmitter.emit (events.js:95:17)
    at exports.all (E:\NodeCG\nodecg\lib\bundles\index.js:59:17)
    at _fulfilled (E:\NodeCG\nodecg\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (E:\NodeCG\nodecg\node_modules\q\q.js:823:30)
```

**Comment by Lange** [comment]
It looks like your bundle's `nodecg.json` has `extension.express` set to `true`, but isn't exporting an express app.

**Comment by Tamfoolery** [comment]
Ha, yep I'm a moron, ta!

**Comment by Lange** [comment]
I'm writing a better error message for this, it's pretty dang vague. Thanks for bringing it to my attention!
